language: node_js
version: 1.0
node_js:
- node
install:
- yarn
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
  - stage: lint
    script: yarn lint
  - stage: test
    script: yarn test:cov
  - stage: build
    script: yarn build
    deploy:
      provider: npm
      email: tanfonto@pm.me
      tag: latest
      skip_cleanup: true
      edge: true
      on:
        tags: true
      api_key:
        secure: fdg/pZhdoRR6ALpakVg/NDDJnocsloCePlTged4dBpc0BVvuHqUPdEKCz5AcrK0Az5xmoHRu1wNWxU3gtgLDukBkCzGAI/4U1OfKyHSAEeTZ+A720hbZQLcS9xdktcM9j9WPqUU0yy+WkPFzn6SbSGnjKhmdW56vuBnQkMcjsKwG6AMWYo2Qq/BAM+uTl0PHEiAoF3QnFb5XssxM2VfQOXcqbETry63jSXoSG1kmfG5/VhkxytrupEQ94gNZwcrn73fAqxF8KI+UB3pML5bFS6au+4eDZOOajZFX1zZxs61CDPj5POFfjDFr2OcQ4+LqxuqC2kD9B8m9Oyy3aq5+aTcEQ7hwd+P45mO2QtYuGEP3z1njBaB8hSabjIdmz82ohjgpt0804HuSW3bc0V8c8oDtqG42I+xCM3RyvQs/zpiEqOb15NzKfJAkVKoC9TbdZwm5djWL+PdqcoxXmpk6mRUIPlyh6BKkzx9j/9emsJm/QRZHnrAEZDHdIihw4GH90oa45CxBm5DaiD5h1uBz1Fxqj0rx1fHAdcb4UajeyVyyY3n++Lt6TSOr5olRTR4AcpeM+LfI5Xk/PidvPtwP8G2Z22oBj3PuOTRVT2ut3GarGSJ1xgvncHYqUM5kKrOwfzH4cbjVHjpMW515Bp/POjewOH+NcOWjzUsJKtUjZaA=
